	%SetNextPreCompiledCodePointer(SCDT_ARAM_GlobalSampleBank_Ptrs, 0, "SPC700/SPC700DataBlocks_SCDT.bin")
	%SetNextPreCompiledCodePointer(SCDT_ARAM_GlobalSampleBank_Main, 1, "SPC700/SPC700DataBlocks_SCDT.bin")
	%SetNextPreCompiledCodePointer(SCDT_ARAM_DATA_3E00, 2, "SPC700/SPC700DataBlocks_SCDT.bin")
	%SetNextPreCompiledCodePointer(SCDT_ARAM_SPC700Engine_Main, 3, "SPC700/SPC700DataBlocks_SCDT.bin")
	%SetNextPreCompiledCodePointer(SCDT_ARAM_SPC700Engine_DATA_3F00, 4, "SPC700/SPC700DataBlocks_SCDT.bin")
